export const createDefaultNotes = () => {
  return [
    {
      id: "1",
      text: "Welcome to Sticky Notes.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
    {
      id: "2",
      text: "A Place to Manage All of Your Notes.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
    {
      id: "3",
      text: "Stay Productive and Organized.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
    {
      id: "4",
      text: "Please Read All Notes Before Using The App.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
    {
      id: "5",
      text: "Pro Tip: Click on the header to reset the form.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
    {
      id: "6",
      text: "Long Notes Can Be Scrolled.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
    {
      id: "7",
      text: "Pro Tip 2: On Mobile Device Click On A Note to Active and Click Outside to Deactivate, Only One Note Can Be active At All Time.",
      dueDate: "dd/mm/yyyy",
      dueTime: "10:30",
      color: null,
      createdAt: null,
    },
  ];
};
